name       : git-flow
version    : 1.12.2
release    : 2
source     :
    - https://github.com/petervanderdoes/gitflow-avh/archive/1.12.2.tar.gz : 9f9345e151fef8fb1049122f9fe5b02af7ec207a2bbfa98700b8940159280c46
license    :
    - BSD-2-Clause
    - LGPL-2.1
component  : programming.tools
summary    : Git extensions to manage branching
description: |
    A collection of Git extensions to provide high-level repository operations for Vincent Driessen's branching model.
rundeps    :
    - git
patterns   :
    - /usr/share/doc/gitflow
install    : |
    install -v -D -m 0755 git-flow $installdir/usr/bin/git-flow
    install -v -D -m 0644 -t $installdir/usr/bin/ git-flow-init git-flow-feature git-flow-bugfix git-flow-hotfix git-flow-release git-flow-support git-flow-version gitflow-common gitflow-shFlags git-flow-config
    install -v -D -m 0755 -t $installdir/usr/share/doc/gitflow/hooks hooks/*
